
DROP TABLE STATEMENT.order_items;  
DROP TABLE STATEMENT.orders;
DROP TABLE STATEMENT.inventories;
DROP TABLE STATEMENT.products;
DROP TABLE STATEMENT.product_categories;
DROP TABLE STATEMENT.warehouses;
DROP TABLE STATEMENT.employees;
DROP TABLE STATEMENT.contacts;
DROP TABLE STATEMENT.customers;
DROP TABLE STATEMENT.locations;
DROP TABLE STATEMENT.countries;
DROP TABLE STATEMENT.regions;